package main

import "go_study_basic/section8"

func main() {

	//section1.Helloworld()
	//section2.Variable1()
	//section2.Variable2()
	//section2.Variable3()
	//section2.Const1()
	//section2.Const2()
	//section2.Enumeration1()
	//section3.If1()
	//section3.Switch1()
	//section3.Switch2()
	//section3.Switch3()
	//section3.For1()
	//section3.For2()
	//section3.For3()
	//section4.InitTest1()
	//section5.Bool1()
	//section5.Numeric1()
	//section5.Numeric2()
	//section5.Number_Operation1()
	//section5.String1()
	//section5.String2()
	//section5.StringOper1()
	//section5.StringOper2()
	//section5.StringOper3()
	//section6.Array1()
	//section6.Array2()
	//section6.Array3()
	//section6.SliceBasic1()
	//section6.SliceBasic2()
	//section6.SliceEx1()
	//section6.SliceEx2()
	//section6.SliceEx3()
	//section6.Map1()
	//section6.Map2()
	//section6.Map3()
	//section6.Map4()
	//section6.Pointer1()
	//section6.Pointer2()
	//section7.Func1()
	//section7.Func2()
	//section7.Func3()
	//section7.Closure1()
	//section8.UserStruct1()
	//section8.UserStruct2()
	//section8.Struct1()
	//section8.Struct2()
	//section8.Struct3()
	//section8.Struct4()
	section8.Struct5()
}
